import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/themeProvider";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modalProvider";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /** Mount Clerk provider here */
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey="harmonyDark">
                <ModalProvider />
                    {children}
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
